name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      env:
        SPRING_DATASOURCE_URL: ${{ secrets.NEON_DB_URL }}
        SPRING_DATASOURCE_USERNAME: ${{ secrets.NEON_DB_USER }}
        SPRING_DATASOURCE_PASSWORD: ${{ secrets.NEON_DB_PASSWORD }}
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      if: success()
      with:
        name: user-service
        path: target/*.jar
